name: "✨ Feature Request"
description: "Request a new feature for Student Risk Analyzer"
title: "[FEATURE REQUEST] "
labels: ["feature request"]
body:
  - type: input
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Describe the feature you want"
      placeholder: "Add CSV export for student ledger"
      required: true

  - type: dropdown
    id: component
    attributes:
      label: "Component"
      options:
        - "Student Dashboard"
        - "Mentor Dashboard"
        - "Data Pipeline"
        - "Risk Engine"
        - "Other"
      required: true
